name: Ubuntu 2204

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  Create_and_push_Intel_xdyn_build_docker_image:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Login to Docker Hub
    #  uses: docker/login-action@v1
    #  with:
    #    username: ${{ secrets.DOCKERHUB_LOGIN }}
    #    password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push the docker image
      run: |
        docker build -t gjacquenot/xdynubuntu .
    - name: Compile
      run: |
        git clone --recursive https://gitlab.com/sirehna_naval_group/sirehna/xdyn
        cd xdyn
        git checkout 69-update-code-so-that-it-compiles-with-ubuntu-22-04-and-gcc-11
        cd ..
        make
